### ISSUE TITLE
`CommitObject` failed to find commit when objects are from `objects/info/alternates`

### ISSUE THREAD

**Issue by harryzcy** [go-git/go-git#1002]
It seems in v5.11.0, `Repository.CommitObject` gives "object not found" when objects are from `objects/info/alternates`. `git cat-file -p <sha>` is able to get commit content in this case. `CommitObject` function also works in v5.9.0.

The the file structure is the following:

```
.
├── branches
├── config
├── description
├── HEAD
├── hooks
│   ├── applypatch-msg.sample
│   ├── commit-msg.sample
│   ├── fsmonitor-watchman.sample
│   ├── post-update.sample
│   ├── pre-applypatch.sample
│   ├── pre-commit.sample
│   ├── pre-merge-commit.sample
│   ├── prepare-commit-msg.sample
│   ├── pre-push.sample
│   ├── pre-rebase.sample
│   ├── pre-receive.sample
│   ├── push-to-checkout.sample
│   └── update.sample
├── index
├── info
│   └── exclude
├── logs
│   └── HEAD
├── objects
│   ├── info
│   │   └── alternates
│   └── pack
├── packed-refs
└── refs
    ├── heads
    └── tags
```

The issue is breaking https://github.com/go-gitea/gitea/pull/28628

**Comment by pjbgf** [comment]
@harryzcy that is due to https://github.com/go-git/go-git/pull/953/commits/8b47ceb1aa854f3c3bfa1c347157a04324fcd51e. In order to revert to previous behaviour, pass on an osfs filesystem via `AlternatesFS`. But take into account the security implications of doing so.

For examples on setting `AlertnatesFS` refer to dotgit tests: https://github.com/go-git/go-git/blob/8b47ceb1aa854f3c3bfa1c347157a04324fcd51e/storage/filesystem/dotgit/dotgit_test.go#L838.
