### ISSUE TITLE
FEAT: Implement IsAdded IsModified IsDeleted method for status

### ISSUE THREAD

**Issue by mowazzem** [go-git/go-git#1143]
As there is an implementation (IsUntracked) for checking Untracked file. It would be better if there are implementation for IsAdded, IsModified, IsDeleted

**Comment by pjbgf** [comment]
Hey @mowazzem, thanks for your suggestion. This functionality already exists, only with a slight different syntax:

```golang
	status, err := w.Status()
	...
	if status.File("my-file").Staging == Added {
		...
	}
	if status.File("my-file").Staging == Deleted {
		...
	}
```

This also support the check at both `Staging` and `Worktree`.

Please note that the only reason why `IsUntracked` exists, is due to the fact that missing entries in the status map are considered `untracked` by definition. Therefore, that [func](https://github.com/go-git/go-git/blob/master/status.go#L29) does two things:

1. It confirm that the entry exists.
2. Checks that its status is `untracked`.

Due to the above, we won't be adding this to `go-git`'s API.
