### ISSUE TITLE
 authentication required

### ISSUE THREAD

**Issue by axetroy** [go-git/go-git#116]
I am cloning a private library

And comes with a username and password

But this doesn't seem to work and got `authentication required` error

```go
	options := git.CloneOptions{
		URL:               getGitURL(r.repo, username, password), // https://username:password@github.com/owner/repo.git
		Progress:          os.Stdout,
		SingleBranch:      true,
		Depth:             1,
		RecurseSubmodules: git.DefaultSubmoduleRecursionDepth,
	}

	_, err := git.CloneContext(ctx, memory.NewStorage(), fs, &options)
```

**Comment by mcuadros** [comment]
Please take a look to https://github.com/go-git/go-git/blob/master/_examples/clone/auth/basic/username_password/main.go

**Comment by axetroy** [comment]
Hi! I checked it. I followed the demo usage method and still throw this error

Here is the option for clone:

`{URL:https://github.com/axetroy/xxx-private.git Auth:http-basic-auth - my_email@gmail.com:******* RemoteName: ReferenceName: SingleBranch:false NoCheckout:false De1 RecurseSubmodules:10 Progress:0xc0001aa008 Tags:0}`

```go
repo, err := git.CloneContext(ctx, filesystem.NewStorage(osfs.New(gitDir), cache.NewObjectLRU(cache.MiByte*50)), fs, &options)

	if err != nil {
		return "", errors.WithStack(err)
	}
```

**Comment by benni-tec** [comment]
Hey, I've got the same issue. I am setting the Auth with correct username and password but it still says "authentication required"

**Comment by axetroy** [comment]
> Hey, I've got the same issue. I am setting the Auth with correct username and password but it still says "authentication required".
> 
> Did you resolve the problem? Or do you an alternative other than putting credentials in the url?

UPDATE:

This seems to be the two-factor authentication that I turned on, so I can’t clone the project with my account/password

**Comment by benni-tec** [comment]
Hmm, thats interesting! I don't think I've got 2FA turned on. 
Funnily when I tried it the next day auth just started to work \_(ツ)_/¯

Thanks for the help though!

**Comment by xkfen** [comment]
i solved by this demo code.
`func gitCloneByBasicAuth(workspace, repoUrl, referenceName string) (*git.Repository, error) {
	var repo *git.Repository
	var err error
	repo, err = git.PlainClone(workspace, false,
		&git.CloneOptions{
			URL:           repoUrl,
			ReferenceName: plumbing.ReferenceName(referenceName),
			Progress:      os.Stdout,
		})
	if err != nil {
		if err == git.ErrRepositoryAlreadyExists {
			// 如果已经存在，就不再clone
			return repo, nil
		}
		return nil, err
	}
	return repo, err
}`

**Comment by taylorfutral** [comment]
So the error message "authentication required" does not make it clear but when I manually tried to do a similar step:

`$ git push --set-upstream origin test-foo
Username for 'https://github.com': yourUserName
Password for 'https://yourUserName@github.com': 
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/yourUserName/ExampleRepo/'`

I realized that the issue was using my **password** instead of the _**Personal Access Token**_ available in developer settings https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token , after that worked fine

`repo, err := git.PlainClone(path, false, &git.CloneOptions{
			Auth: &http.BasicAuth{
				Username: username,
				Password: personalAccessToken,},
				URL: "https://github.com/go-git/go-git",
				Progress: os.Stdout,
		})`
