### ISSUE TITLE
Relative submodule URL broken

### ISSUE THREAD

**Issue by l-ehlers** [go-git/go-git#1195]
We have a submodule specified by relative path

```
[submodule "lib"]
        path = lib
        url = ../../../../../path/to/submodule
```

Cloning it with the git CLI is no problem, but go-git errors with `repository not found` (on `submodule.UpdateContext`, more precisely on fetching the submodule). My theory is that the following change has broken relative submodule paths for all protocols but "file". 

https://github.com/go-git/go-git/pull/756/files#diff-4859e2ed735a237fdd30551432a11503c3d3a70a5ff9ea6e3147db1679d8b878R141

Is there a reason for this or is this a bug? :)

Edit: Adding more context.. I am trying to clone the main repository and initialize and update the submodule.

**Comment by pjbgf** [comment]
@l-ehlers can you please share a code snippets that reproduces the problem?

**Comment by l-ehlers** [comment]
I cannot share the full code as it is company-owned. I have tried to reproduce it in a small repository but failed so far.

In our use case, we have different access tokens for the main repository and the submodule, maybe this results in the error.

But I see, this bug report does not really help if it is not reproducible, so I will post it again as soon as I can reproduce it in public code.

**Comment by pjbgf** [comment]
@l-ehlers the first thing that would come to mind is that submodules in disk using a relative path may not be found due to the filesystem (`osfs` vs `memfs`) being used, and also the lack of the option of setting one atm.

> we have different access tokens for the main repository and the submodule
This won't have an impact, as based on what you are saying the submodule is being opened from disk, so you wouldn't need a token.

Is there any chance that you can set the actual url in `url`, instead of a relative path? If you can't change that, you would be able to workaround this by first doing the clone of the submodules using the external URL and token details, then cloning/opening of the repository that depends on it. But then you still may encounter the issue I mentioned on the first sentence.
