### ISSUE TITLE
go-git pull tags  probem

### ISSUE THREAD

**Issue by junun** [go-git/go-git#122]
In my local repo directory do `git log`
```
commit 195ab39df51143be4441b591b82c00e9c43365e8 (HEAD -> master, origin/master)
Author: junun <jun.liu@topc.com>
Date:   Mon Jul 6 10:49:19 2020 +0800

    +测试文件

commit 83299be9efc670c8316c99c0a569faf6dd488d8e (tag: v1.4, tag: v1.3, tag: v1.2, tag: v1.1, tag: v1.0)
Author: junun <jun.liu@topc.com>
Date:   Sat Apr 11 10:31:12 2020 +0800

    +添加images.topc.com
```
In my project use go-git Pull  and do `git log`
```
commit 195ab39df51143be4441b591b82c00e9c43365e8 (HEAD -> master, origin/master)
Author: junun <jun.liu@topc.com>
Date:   Mon Jul 6 10:49:19 2020 +0800

    +测试文件

commit 83299be9efc670c8316c99c0a569faf6dd488d8e (tag: v1.3, tag: v1.2, tag: v1.1, tag: v1.0)
Author: junun <jun.liu@topc.com>
Date:   Sat Apr 11 10:31:12 2020 +0800

    +添加images.topc.com
```

go-git Pull cannot pull tags info.
anyone help me?

**Comment by Vialeon** [comment]
If you use go-git Clone into a temporary directory and then use git log on that directory is this replicated?

**Comment by nzin-appdirect** [comment]
I had the same issue, I had to
```
	err = r.Fetch(&git.FetchOptions{
		RemoteName: "origin",
		Tags:       git.AllTags,
	})
	if err != nil && err != git.NoErrAlreadyUpToDate {
		return err
	}
```

**Comment by gwd** [comment]
I've intermittently had issues like this as well.  Here's a report from a colleague on a tool I wrote which uses go-git internally:

https://gitlab.com/xen-project/people/gdunlap/go-xenlib/-/issues/1

The tool keeps a local "cache" of an upstream repo which it updates occasionally.  The initial clone and subsequent fetches are all done with go-git; obviously it *usually* gets tags with a fetch.  But sometimes it seemed to get into a state where it thought there were no updates but there were.  Manually executing "git fetch" in the repo seemed to fix the issue.

**Comment by gwd** [comment]
Last instance I had of something *like* this was back in June (and before that in May), using go-git v5.4.2.  In this case it actually started throwing a strange error message:

```
2023/07/25 16:58:02 Error calling xeninfo.Update(): Updating repo: reference has changed concurrently
```

Note that:

 * There's exactly one script, being run daily by `cron`, which accesses the repo in question
 * The exact same error repeated every day for three days
 * The error was resolved by running "git fetch" from the repo in question

I'm guessing what's happened is that (perhaps in response to this error or something like it) someone added some extra checking, and that the checking has detected whatever invariant ended up being violated that caused this problem.

I'll update to the latest version of go-git and report any further issues here as they happen (to keep the bots happy).

**Comment by pjbgf** [comment]
@gwd I am under the suspicious that this happens when the remote reference changes during the fetch operation. For example, when the `HEAD` of the branch being cloned changes during that process, while someone else commits/merges into the remote branch. Do you think that could be the case here? 

When you referred tp `git fetch` do you mean you had to shell out to the `git` cli in order to workaround the issue or an additional Git fetch via `go-git` did the trick?

For reference, the second part of this issue is a duplicate of https://github.com/go-git/go-git/issues/37.

**Comment by gwd** [comment]
@pjbgf  Thanks for the response.  To answer the second question: My recollection is that running my tool again manually (which did a fetch using  `go-git`) had exactly the same issue; but that opening up a shell, cd'ing to the appropriate directory, and executing `git fetch` using the canonical upstream git fixed the issue.

Of course it's quite possible that *at some point* the remote HEAD changed while my script was doing a fetch; collaboration is what git is for, after all.  That HEAD happened to change *every time the script ran*, even when run manually, until I executed `git fetch` from a shell prompt, and then never again thereafter, seems pretty unlikely.

FWIW I don't think I've had this issue since the above-mentioned error in June 2023.
