### ISSUE TITLE
git branch --contains <revision>  [Help]

### ISSUE THREAD

**Issue by zwfang** [go-git/go-git#131]
Hello,
I want to list all branches that contains the given revision. Is there a way to implement it in go-git?

**Comment by JamesArthurHolland** [comment]
Has there been any update on this? Pretty important use case.

Even if there was a way to loop through the commits of a branch as a work around?

Can't find a way to create a log iterator that only logs specific branch commits

**Comment by enrichman** [comment]
I had the same need and I think I've found a workaround.

Basically you need to use the Log to read all the commits of the reference, this is an example:

```go
repo, _ := git.PlainCloneContext(context.Background(), "myrepo", false, &git.CloneOptions{
    URL: "https://github.com/username/myrepo",
})

fmt.Println("iterating commits in default branch")
commitIter, _ := repo.Log(&git.LogOptions{Order: git.LogOrderCommitterTime})

var count int
_ = commitIter.ForEach(func(c *object.Commit) error {
    count++
    return nil
})
fmt.Println("commits", count)

///////// check for remotes

w, _ := repo.Worktree()

fmt.Println("iterating references")
refIter, _ := repo.References()

_ = refIter.ForEach(func(r *plumbing.Reference) error {
    if r.Name().IsRemote() {
        fmt.Println("branch: ", r.Name().Short())

        _ = w.Checkout(&git.CheckoutOptions{
            Branch: r.Name(),
            Force:  true,
        })

        fmt.Println("iterating commits in branch", r.Name().Short())
        commitIter, _ := repo.Log(&git.LogOptions{Order: git.LogOrderCommitterTime})

        var count int
        _ = commitIter.ForEach(func(c *object.Commit) error {
            count++
            return nil
        })
        fmt.Println("commits", count)
    }
    return nil
})
```

since the branches are usually starting from the same commits of the default branch in my case I improved a bit the functionality adding a map that will check for the already seen commits, and avoid to go back to the starting point.

Anyway, adjust this snippet to your needs. It should do the job. :+1:
