### ISSUE TITLE
cloning with gitmodule gives me `entry not found` error

### ISSUE THREAD

**Issue by genshen** [go-git/go-git#145]
cloning with gitmodule gives me `entry not found` error
```go
if repos, err := git.PlainClone("csv-parser", false, &git.CloneOptions{
	URL:      "https://github.com/vincentlaucsb/csv-parser.git",
	Progress: os.Stdout,
	//ReferenceName: referenceName, // specific branch or tag.
	RecurseSubmodules: git.DefaultSubmoduleRecursionDepth,
}); err != nil {
	log.Println(err) // Print error here
}
```

I notice that, in repo 'https://github.com/vincentlaucsb/csv-parser.git' (e.g. version 1.3.3),  there is a . gitmodules file and specified directory 'lib/sqlite-cpp' as submodule (but this directory does not exists in repo).  

But it works fine when I use git command:
```
git clone git@github.com:vincentlaucsb/csv-parser.git
git submodule update --init --recursive
```

**Comment by hwwwi** [comment]
@genshen 
Hello, I had the same issue with the submodule. 
It's a bit confusing since the git CLI silently ignores the broken git submodule which is different from go-git.
I think it's better to remove .gitmodule file if you are not using the submodule anymore or add the git submodule directory in your repo. 
The git submodule command will not work without the submodule directory anyway.

**Comment by dikkini** [comment]
i also have an issue with submodules.

i have an error: repository not found

my submodules looks like this:
```yaml
[submodule "libs/ansible-lib"]
  path = libs/ansible-lib
  url = ../ansible-lib.git
```

**Comment by per1234** [comment]
>I can suppose that library does not support relatives paths in submodules

There is now a dedicated issue about that (resolved) bug: https://github.com/go-git/go-git/issues/266

**Comment by pjbgf** [comment]
Closing this as it has been pointed out as fixed above.
