### ISSUE TITLE
git upload-pack / receive-pack

### ISSUE THREAD

**Issue by ghost** [go-git/go-git#152]
Hi,

I have a simple piece of code in Go.
```
out, err := exec.Command("git", "upload-pack", "--stateless-rpc", "--advertise-refs", "/path/to/repo.git").Output()
```

I wonder if and how can I replace this command call with go-git library?
I haven't found any example or documentation so I'm asking here.

**Comment by riyaz-ali** [comment]
I assume, since you're trying to execute `git-upload-pack`, that you're trying to _serve_ some repository from a remote server.

I guess `go-git` currently doesn't natively support handling the remote end of `git` transports .. I does provide client implementations for various transports in the [`transport`][1] package but only provides a _generic_ implementation for the [`server`](2) transport.

That means you'd still have to write some code to translate between protocol layers such as implementing an http handler that support [`git`'s Smart HTTP protocol][3] utilising the [`server` transport][2] to do the _actual heavy lifting_ of dealing with reference advertisement and repository update.

Or you could utilise the binaries in [`cli/go-git` directory][4] in which case it'd essentially be the same as invoking `git` directly as you're doing now.

[1]: https://github.com/go-git/go-git/tree/master/plumbing/transport
[2]: https://github.com/go-git/go-git/tree/master/plumbing/transport/server
[3]: https://github.com/git/git/blob/master/Documentation/technical/http-protocol.txt
[4]: https://github.com/go-git/go-git/tree/master/cli/go-git
