### ISSUE TITLE
Worktree.Commit() read git config user data

### ISSUE THREAD

**Issue by aellwein** [go-git/go-git#19]
Hi,

i want to do a Git commit from my code programmatically, without having the user to provide any information, like ``CommitOptions``.  As with standard ``git`` command, i would expect git to fall back to globally configured ``user.name`` and ``user.email``.  Can this be done also with go-git?

P.S.: there is a segfault in ``Worktree.Commit()`` if nil passed for ``&CommitOptions``.

**Comment by mcuadros** [comment]
Short answer is no. 

The global config is a very porcelain stuff and go-git still is focused on building the plumbing. It's, even more, the access to the filesystem is limited by the folder provided on the `Init` or `Clone` command, so it is really hard to read a folder from the HD without breaking the full paradigm behind the storers.

If anyone wants to contribute to this feature as a good starting point could be adding the user information to the [`config.Config`](https://pkg.go.dev/github.com/go-git/go-git/v5/config?tab=doc#Config) struct since this information is not even parsed. With this should be easy to create the default `CommitOptions` reading the config file outside of the `go-git` code.

**Comment by aellwein** [comment]
Ok, understood. Mind if i go ahead and try to implement the above in a pull request?

**Comment by mcuadros** [comment]
Just by chance, someone is working something very related https://github.com/go-git/go-git/pull/20
So wait at least to see the outcome of the PR

**Comment by aellwein** [comment]
Yes, using scoped config feature i am now enabled to fill the config data from system/global git configuration. Thanks!
