### ISSUE TITLE
How to handle repositories without branches / HEAD only?

### ISSUE THREAD

**Issue by hashworks** [go-git/go-git#270]
I'm currently working with many repositories, a few them have no branch set:
```
$ git clone https://aur.archlinux.org/sfdx-cli.git
Cloning into 'sfdx-cli'...
remote: Enumerating objects: 321, done.
remote: Counting objects: 100% (321/321), done.
remote: Compressing objects: 100% (179/179), done.
remote: Total 321 (delta 142), reused 321 (delta 142), pack-reused 0
Receiving objects: 100% (321/321), 47.65 KiB | 920.00 KiB/s, done.
Resolving deltas: 100% (142/142), done.
Note: switching to '5a901e8a8024e0589db74c6427cb60c7318db500'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

$ cd sfdx-cli
$ git branch
   * (no branch)
$ cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://aur.archlinux.org/sfdx-cli.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

Trying to `PlainClone` one of them results in `ErrReferenceNotFound` (`unexpected client error: reference not found`). Same if I already cloned it and try to `PlainOpen` and `Fetch` an existing local repo.

Any idea?

**Comment by sata** [comment]
I had the same problem when trying to clone a repository running in a Travis PR task. 

Reason for it seems to be not just the fact it's in detached head state, but the fact that the Travis PR job does a merge of the feature branch in detached head state. I.e there are no refs for the given commit.

if I do `git branch foo` before running my program, `go-git` behaves as expected, this is due to the fact that the commit referred by `refs/head/foo` exists and `go-git` can `figure out` what `head` is. https://github.com/go-git/go-git/blob/bf3471db54b0255ab5b159005069f37528a151b7/plumbing/protocol/packp/advrefs.go#L105

In the case of cloning over file transport, I wonder why looking at `.git/HEAD` isn't enough and why we need to resolve head from refs which isn't always possible if a commit isn't referenced.

I'll try to understand this a bit better and see what would break we don't try to resolve head from refs.

**Comment by pjbgf** [comment]
I could not reproduce this with on `v5.11.0` using the `clone` example:
```
$ go run _examples/clone/main.go https://aur.archlinux.org/sfdx-cli.git /tmp/git2
git clone https://aur.archlinux.org/sfdx-cli.git /tmp/git2 --recursive
commit 43a051332790380ac751da7bf563c74e1bf1c2a9
Author: Dang Mai <contact@dangmai.net>
Date:   Fri Jul 14 02:36:30 2023 +0000

    Updated to 7.209.6
```

**Comment by hashworks** [comment]
That is because the repo in question does have a proper branch now.
