### ISSUE TITLE
How to create orphan branch

### ISSUE THREAD

**Issue by afdecastro879** [go-git/go-git#370]
Hi All!

I'm struggling understanding how can I create an orphan branch using this library. Normally you can achieve this with git doing:

```
git checkout --orphan <new_branch>
```

**Comment by john-cai** [comment]
https://github.com/go-git/go-git/pull/439

**Comment by lacarvalho91** [comment]
@afdecastro879 

I've been looking into this and it turns out that all you need to do to create an orphaned branch is:
```golang
repo.Storer.SetReference(plumbing.NewSymbolicReference(plumbing.HEAD, myNewBranch))
```

This replicates `git checkout --orphan myNewBranch`

If you want the `git switch --orphan myNewBranch` behaviour instead (which is to create a new orphaned branch with a clear index) then you can do:
```golang
wt, err := repo.Worktree()
wt.RemoveGlob("*")
```

**Comment by jmgilman** [comment]
@lacarvalho91 I was unable to get your example to work. Are you doing anything before that step? Any subsequent step after running `SetReference` fails with various errors. I'm assuming it's because something internally is getting messed up.
