### ISSUE TITLE
git-ssh: try multiple algorithms for known_hosts

### ISSUE THREAD

**Issue by franklouwers** [go-git/go-git#411]
Hi,

When using git over ssh, it seems that if a host (eg: GitHub.com) has multiple keys (eg: an rsa and an ed25519 ones), but only one of those keys is listed in the `$HOME/.ssh/known_hosts`, and the one that's not listed has a higher preference (e.g. ed25519 over rsa), then the git clone operation will fail.

I feel it should try to be more intelligent and try to use the rsa one.

**Comment by steffakasid** [comment]
I experienced the same. As workaround you could do the following: `ssh-keyscan github.com >> known_hosts`

**Comment by mojotx** [comment]
I've been struggling for several days, trying to get go-git to work, and I kept thinking it had something to do with ssh-agent, or that I had missed some minor thing in my code. 

THIS was the problem, and running `ssh-keyscan github.com >> ~/.ssh/known_hosts` fixed it for me.

**Comment by mojotx** [comment]
I did some digging, to see how easy this would be to fix, and I don't think this is an issue in [go-git](https://github.com/go-git/go-git)'s code

In [plumbing/transport/ssh/common.go](https://github.com/go-git/go-git/blob/f0b111ab70e4e90013658b0835929b2083902017/plumbing/transport/ssh/common.go#L158), in the `dial()` func, the code is calling ssh.NewClientConn(). 

```go
	c, chans, reqs, err := ssh.NewClientConn(conn, addr, config)
```

That function is actually defined in [golang/x/crypto/ssh](https://pkg.go.dev/golang.org/x/crypto/ssh#NewClientConn). I didn't follow the rabbit trail all the way down into the crypto code, but I suspect that's where it needs to be fixed. 

If I had the time, I would try writing a trivial Go program that makes a SSH connection to Github,, disabling the pseudo-tty allocation, which would be the equivalent of `ssh -T git@github.com`. 

Currently if you do that, and you have your SSH keys set up correctly, it prints something like this:

```
$ ssh -T git@github.com
Hi mojotx! You've successfully authenticated, but GitHub does not provide shell access.
```

If a trivial Go implementation of `ssh -T git@github.com` also gives you the same host-key error, then we know for sure that the problem is in the golang/x/crypto/ssh code. 

For what it's worth, I tried forking the go-git repo, and then updating the crypto module, to see if it's been fixed already, and it hasn't. 

```
$ go get -v -u golang.org/x/crypto
go get: upgraded golang.org/x/crypto v0.0.0-20210711020723-a769d52b0f97 => v0.0.0-20211215153901-e495a2d5b3d3
go get: upgraded golang.org/x/net v0.0.0-20210326060303-6b1517762897 => v0.0.0-20211112202133-69e39bad7dc2
go get: upgraded golang.org/x/text v0.3.3 => v0.3.6
```

**Comment by jaredallard** [comment]
Here's a workaround for `~/.ssh/known_hosts` for those running into this:


```
ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
ssh-keyscan -t ecdsa github.com >> ~/.ssh/known_hosts
```

This seems to 100% of the time ensure this works. It's kinda confusing.

**Comment by rgalanakis** [comment]
@jaredallard and others, thank you for the workarounds!

**Comment by smveloso** [comment]
From https://github.com/go-git/go-git/issues/411#issuecomment-996166392:

> I did some digging, to see how easy this would be to fix, and I don't think this is an issue in [go-git](https://github.com/go-git/go-git)'s code

It seems that the root cause is indeed in golang's ssh library: https://github.com/golang/go/issues/29286

However, it's possible to work around it in code by explicitly setting the HostKeyAlgorithms field of https://pkg.go.dev/golang.org/x/crypto/ssh#ClientConfig. This was suggested [here](https://github.com/golang/go/issues/29286#issuecomment-986900028).

I did try and it works. You can see it [here](https://github.com/smveloso/go-git/commit/87192ca512bec4cace5b3159a5fa69d04f605816) (crude implementation; I hardcoded the ssh key type I actually had in my known_hosts). 

I don't know what would be the appropriate way of doing this kind of configuration on go-git. :thinking:

**Comment by evanelias** [comment]
I've just submitted a new pull request #548 which adds auto-population of `ssh.ClientConfig.HostKeyAlgorithms`, based on the known_hosts entries for the git remote host. Seems to work properly and solve this issue in my testing :)

**Comment by shaftoe** [comment]
@evanelias looks great! thanks a lot
