### ISSUE TITLE
object not found

### ISSUE THREAD

**Issue by daniel-mode** [go-git/go-git#432]
Hello.

I'm getting an `object not found` error when trying to do a Fetch using the following code:

```
_, err = repo.CreateRemote(&config.RemoteConfig{
Name: remote,
URLs: []string{url},
})

list, err := repo.Remotes()
for _, r := range list {
	fmt.Println(r)
}
err = repo.Fetch(&git.FetchOptions{
	RemoteName: remote,
})
```

The remotes printout display the recently created remote. The same logic works when using the git command line.
I copied part of this code from:  https://github.com/go-git/go-git/blob/master/_examples/remotes/main.go
I'm using version: github.com/go-git/go-git/v5 v5.4.2.

Thanks for your help.

**Comment by daniel-mode** [comment]
To clarify, the following line of code works, note that it uses the same Remote as the previous code:

fetchCmd := exec.CommandContext(ctx, "git", "fetch", remote, branch)

**Comment by macstevens-bread** [comment]
I noticed that this occurs when the remote branch has been deleted. I have a possible fix in a fork and I'll try to get a PR up

**Comment by dfelici87** [comment]
Hi, 
I have the same problem, can you fix it asap?

Thanks!

**Comment by macstevens-bread** [comment]
Hey, as an FYI, the fix is in this fork https://github.com/getbread/go-git/tree/TOOLS-363-handle-remote-branch-delete

Just as a full disclosure, tomorrow is my last day at the company where I made the fix but my team is going to pick it up and hopefully get a PR submitted. Some testing still needs occur and the package org will need to be changed from getbread to go-git.
