### ISSUE TITLE
What operations are concurrency safe and I can call from different Goroutines?

### ISSUE THREAD

**Issue by mkhadilk** [go-git/go-git#48]
I am currently doing ALL 'non-modification' operations like 'diff', get commit details, get files in commit, get parent etc.

Can I call  such read only APIs from different go routines?

**Comment by mcuadros** [comment]
go-git is not thread-safe, this is due to not having mutex in the write operations. But also, could be potentially problematic for reading operations since some areas are using caches, and this may cause problems. 

We didn't make evaluation of this, and personally I never used it in a concurrent mode for a single repository. But it's an interesting topic.

**Comment by mkhadilk** [comment]
**Thank you very much**. I fortunately had a strong abstraction layer to go to Git calls. I landed up putting a single Git access mutex. I lock and unlock when actually access.
The only problem was re-entrant access but I was able to unwrap those calls and make some of then private.
So for not, I am ok.

**Comment by lrstanley** [comment]
Noticed it wasn't thread safe myself, as I'm working on a project that gets matching file objects, and passes them to large group of goroutines to concurrently scan each object for specific tokens (scanning for `TODO`'s and similar), to be more efficient, it reads the file as an io.Reader rather than all at once, which means there are concurrent calls to `plumbing/object.GetBlob()` to get the reader as well as in the `TreeWalker`, that are definitely not concurrent safe. It seems after getting the io.Reader, I don't think I have to worry about concurrency, so it's mainly the function calls to the library.

Will wrap the calls against these with a mutex for now, but would definitely be nice to see the library thread-safe.

**Comment by kaihendry** [comment]
Hi, I've hit `fatal error: concurrent map read and map write` and I don't even understand what the write is, since I'm reading in my loop: https://gist.github.com/kaihendry/748b57905d35403751be2f4aac6cd40f#file-main-go-L75-L95

Is there some way to speed up raading the commit's line Addition/Deletions? 

Are is concurrency just ruled out? https://github.com/src-d/go-git/issues/457

Thank you!

**Comment by pjbgf** [comment]
@kaihendry thank you for sharing some code to make it easier to reproduce the problem.

I managed to get your code working with 10 concurrent go routines by using memory storage with three additional changes:
- https://github.com/go-git/go-git/pull/175 (this will remove the panic)
- https://github.com/fluxcd/go-git/pull/14 (this will ensure the results' accuracy)
- Adding a `wg.Wait()` at the end of your code.

Here's a full end to end using the Flux' fork: https://gist.github.com/pjbgf/45eb717606f4857661e071f6249f4225
I will do a few more tests and performance benchmarks before I submit https://github.com/fluxcd/go-git/pull/14 upstream (here).

I don't think this will resolve all concurrent use cases, but could be a start.

**Comment by kaihendry** [comment]
It appears about 4x faster (200 it/s versus 50 it/s) when using 10 concurrent go routines in local random repo! :fire: 

Oddly with https://github.com/kaihendry/lesshero/blob/main/main_test.go it doesn't seem faster at all though. I must be doing something wrong!

**Comment by d4x1** [comment]
I think it should be reopened because there still exists such problems.

**Comment by pjbgf** [comment]
@d4x1 there is a big overlap between this and #773, so instead of having two issues on the same subject, let's track the work on the issue that is open instead.
