### ISSUE TITLE
"reference delta not found" while cloning / parsing the packfile

### ISSUE THREAD

**Issue by ZauberNerd** [go-git/go-git#484]
We have seen the `reference delta not found` error message while cloning a repository.

We created a minimal reproducible example: https://github.com/ZauberNerd/go-git-external-ref-thinpack

We already saw two other issues and a merged PR, mentioning this error message:
* https://github.com/go-git/go-git/issues/336
* https://github.com/go-git/go-git/issues/391

But those seem to only mention AWS CodeCommit (and we are on GHES) and even with https://github.com/go-git/go-git/pull/392 by @ga-paul-t merged, our reproducer is still able to reproduce the issue, therefore we are not sure, if it is the same issue or related in some other way.

Steps to reproduce:
1. `git clone git@github.com:ZauberNerd/go-git-external-ref-thinpack.git`
2. `cd go-git-external-ref-thinpack/`
3. `git submodule update --init --recursive`
4. `go run main.go`

**Comment by ajaykn** [comment]
I am also facing the similar error `reference delta not found` when doing `git.PlainClone`, 
but no issue with normal `git.Clone`

logged with more details: https://github.com/go-git/go-git/issues/495

**Comment by per1234** [comment]
I thought maybe an additional sample would be useful so I'll share my findings:

Using `github.com/go-git/go-git/v5@v5.4.2`, I unexpectedly encountered the "`reference delta not found`" error when using `github.com/go-git/go-git/v5/git.PlainClone` with the following three repositories:

- https://github.com/RAKWireless/RAK14012-LED-Matrix
- https://github.com/RAKWireless/RAK12021-TCS37725
- https://github.com/hideakitai/Dynamixel

After updating to  `github.com/go-git/go-git/v5@a5bbcd278ab1467bf9a8dfa615649b6c4d699119` or  `github.com/go-git/go-git/v5@c785af3f4559ebac52c42f12d17cb118aac383ad` the problem was resolved for the first two, but not for https://github.com/hideakitai/Dynamixel. The error for that repository is only resolved when using the version of `github.com/go-git/go-git` from https://github.com/go-git/go-git/pull/485
