### ISSUE TITLE
Reference delta not found

### ISSUE THREAD

**Issue by williamchitto** [go-git/go-git#556]
I found this error
"reference delta not found"
 while trying to clone a repository, using the PR https://github.com/go-git/go-git/pull/485 worked for my, can you merge it?

**Comment by bacherfl** [comment]
I also had the same problem when using v5.4.2, but it seems like this has been fixed in the meantime since #392 has been merged in the meantime. After updating go-git to the latest master version this was solved in my case, but it would be great to have an official release version including this fix. Are there any plans to put out a new release any time soon, since 5.4.2 has been released over a year ago?

**Comment by blmayer** [comment]
Hi @williamchitto the MR you mentioned has been merged. Did it fix your issue?
