### ISSUE TITLE
Sponsoring?

### ISSUE THREAD

**Issue by blmayer** [go-git/go-git#678]
I think that setting up sponsoring on this repo can improve its development. This is the only go project (AFAIK) to implement git in pure Go, and it has over 4.2k stars. So sponsoring may be a way to speed up the development as it is ready slow now. What do you think?

**Comment by pjbgf** [comment]
It would be good to get the core maintainers view on this. Potentially some of the companies that depend on `go-git` could help sponsoring.

**Comment by mcuadros** [comment]
The main pris havingt have a sponsor is having time. 

I started this project when I was paid source{d}; we payed several people to contribute to this project for some years. Unfortunately, the company when bankrupt a few years ago, and I joined a new company where we keep using `go-git` at our core. As in source{d}, we use just the pumping to analyze git commits.

In my personal time, I made a considerable effort to add the porcelane to do a proper release covering the basic functionality of git.

This was a few years ago; even if I find a couple of free hours to contribute, it's hard. I am no longer familiar with the code base since it is massive, and the last time I contributed to it was some years ago. And at my company, we don't need new functionality, so we don't have paid time to contribute to go-git.

The ideal situation is that someone with enough knowledge and time leads the project.  

Meanwhile, I will keep doing what I did for the last three years: review the PRs and merge if it follows the general guidelines.
