### ISSUE TITLE
Is it possible to compile go-git to WASM?

### ISSUE THREAD

**Issue by nikitavoloboev** [go-git/go-git#716]
I want to use Git commands in browser. There is [wasm-git](https://github.com/petersalomonsen/wasm-git) project that wraps over [libgit2](https://libgit2.org) that is written in C.

I would love to use go-git compiled to WASM with [TinyGo](https://tinygo.org/getting-started/overview/). Is it possible?

I was trying to read the code and look at examples and am confused if I was to compile go-git to WASM, where would I start?

**Comment by pjbgf** [comment]
It looks like TinyGo does [not support](https://tinygo.org/docs/reference/lang-support/stdlib/#encodinggob) `encoding/gob` yet, so trying to compile the clone example fails:

```
$ tinygo build -o wasm.wasm -target wasm --no-debug _examples/clone/main.go

/usr/local/go/src/encoding/gob/decode.go:597:21: undefined: reflect.MakeMapWithSize
```

Alternatively you could cross-compile to wasm:
```
$ GOOS=js GOARCH=wasm go run main.go
```

Note that for that to work you need `go_js_wasm_exec` in your PATH:
```
go install github.com/agnivade/wasmbrowsertest@latest
cp $GOPATH/bin/wasmbrowsertest $GOPATH/bin/go_js_wasm_exec
```

More info at https://zchee.github.io/golang-wiki/WebAssembly/.

In the same way as with `wasm-git`, you won't be able to clone a github.com repository without using some sort of proxy, due to CORS restrictions.

**Comment by HarikrishnanBalagopal** [comment]
With Go v1.21 can we please add support for `GOOS=wasip1` ?

**Comment by pjbgf** [comment]
@HarikrishnanBalagopal do you mind creating a new issue for adding WASI Support please? We probably should ensure full support at [go-git/go-billy](https://github.com/go-git/go-billy) first.

**Comment by HarikrishnanBalagopal** [comment]
@pjbgf sorry for the late reply. I guess there's already a PR for it now? https://github.com/go-git/go-billy/pull/36

**Comment by pjbgf** [comment]
@HarikrishnanBalagopal the `go-billy` PR is now merged. Now we need to add support to `go-git`, which would include some CI tests and updating docs (e.g. [compatibility.md](https://github.com/go-git/go-git/blob/master/COMPATIBILITY.md)).
