### ISSUE TITLE
A new release with the updated dependencies github.com/ProtonMail/go-crypto

### ISSUE THREAD

**Issue by lyonlai** [go-git/go-git#818]
👋  I was notified by our information security team that the dependency of `github.com/ProtonMail/go-crypto` is suffered from a panic caused by an empty EdDSA public key, this issue could cause denied of service. The issue is fixed in [this commit](https://github.com/ProtonMail/go-crypto/commit/fea64f7572b810f5d1f32b4b5edb0c02bcf28164).  My project has a transitive dependency to it via `go-git`. 

The current master of `go-git` has `v0.0.0-20230717121422-5aa5874ade95`, which is later than `fea64f7572b810f5d1f32b4b5edb0c02bcf28164` but there's no tag for it yet. 

The latest tag v5.8.0 has a slightly earlier version `v0.0.0-20230518184743-7afd39499903`. Could you make a new release for `go-git` so that we could use newer version of `go-crypto`?

Thanks ahead.

**Comment by IronGeek** [comment]
FWIW

The tag `v5.8.0` also still has `github.com/imdario/mergo v0.3.15` as dependency instead of `dario.cat/mergo v1.0.0` despite a [fix](https://github.com/go-git/go-git/commit/efe3292fb1c0b275872ee1e40ccd63d4946083af) is already merged on the same day the `v5.8.0` is released. Which let me to believe that the issue with https://github.com/imdario/mergo/issues/240 has been fixed in v5.8.0... which apparently has not.

**Comment by pjbgf** [comment]
Both changes are already merged on `master`, I recommend using the pseudo version (`github.com/go-git/go-git/v5 v5.8.1-0.20230724090051-36477e82f226`) as I am not sure exactly when a new release will be cut:

```
$ go get github.com/go-git/go-git/v5@master
```

At present that version includes `v5.8.0` plus the dependencies bump and some documentation changes. [Here's](https://github.com/go-git/go-git/compare/v5.8.0...master) a full list of the changes on master since that release.

**Comment by mcuadros** [comment]
Fixed https://github.com/go-git/go-git/releases/tag/v5.8.1
